"""
Generate synthetic decoder parity reference tensors for exp22 and exp23.

Deterministic synthetic tensors with known detections at specific anchor points.
NOT generated by NCNN inference; used to verify decoder logic parity across platforms.

Tensor layout: flattened [OUTPUT_HEIGHT, OUTPUT_WIDTH] row-major.
Detection placed at anchor point 0 (stride=8, center=(0,0)) with:
  - Class score high enough to pass threshold (0.05)
  - DFL logits with one dominant bin -> deterministic expected distances
"""
import json, hashlib, math, os

OUTPUT_HEIGHT = 3598
STRIDES = [8, 16, 32, 64]
INPUT_SIZE = 416
REG_MAX = 7
SCORE_THRESHOLD = 0.05
NMS_THRESHOLD = 0.6


def softmax(logits):
    max_l = max(logits)
    exps = [math.exp(l - max_l) for l in logits]
    s = sum(exps)
    return [e / s for e in exps]


def generate_detection_tensor(num_classes, output_width, class_index, class_score, dominant_bin):
    """Create a tensor with one detection at anchor point 0."""
    assert output_width == num_classes + 4 * (REG_MAX + 1)
    tensor = [0.0] * (OUTPUT_HEIGHT * output_width)

    # Row 0, anchor point 0 (stride=8, center=(0,0))
    row_offset = 0
    # Class scores
    tensor[row_offset + class_index] = class_score
    # DFL logits: dominant bin gets 10.0, others get 0.0
    for side in range(4):
        base = row_offset + num_classes + side * (REG_MAX + 1)
        tensor[base + dominant_bin] = 10.0

    return tensor


def compute_expected_candidates(num_classes, class_names, output_width, tensor):
    """Compute expected decoder output (Kotlin-matching algorithm)."""
    candidates = []
    offset = 0
    for stride in STRIDES:
        feature_size = math.ceil(INPUT_SIZE / stride)
        for y in range(feature_size):
            for x in range(feature_size):
                point = offset + y * feature_size + x
                center_x = x * stride
                center_y = y * stride
                if center_x >= INPUT_SIZE or center_y >= INPUT_SIZE:
                    continue

                row = point * output_width
                # Find best class
                class_idx = 0
                max_score = tensor[row]
                for c in range(1, num_classes):
                    if tensor[row + c] > max_score:
                        max_score = tensor[row + c]
                        class_idx = c

                if max_score < SCORE_THRESHOLD:
                    continue

                # DFL distances
                distances = []
                for side in range(4):
                    base = row + num_classes + side * (REG_MAX + 1)
                    logits = [tensor[base + b] for b in range(REG_MAX + 1)]
                    probs = softmax(logits)
                    expectation = sum(p * b for b, p in enumerate(probs))
                    distances.append(expectation * stride)

                left = max(0.0, min(center_x - distances[0], float(INPUT_SIZE)))
                top = max(0.0, min(center_y - distances[1], float(INPUT_SIZE)))
                right = max(0.0, min(center_x + distances[2], float(INPUT_SIZE)))
                bottom = max(0.0, min(center_y + distances[3], float(INPUT_SIZE)))

                candidates.append({
                    "classIndex": class_idx,
                    "className": class_names[class_idx],
                    "score": max_score,
                    "point": point,
                    "box": [left, top, right, bottom]
                })

        offset += feature_size * feature_size

    return sorted(candidates, key=lambda c: -c["score"])


def generate_reference(exp_name, num_classes, class_names, output_width,
                       class_index, class_score, dominant_bin,
                       param_sha256, bin_sha256):
    """Generate complete reference JSON."""
    tensor = generate_detection_tensor(num_classes, output_width, class_index, class_score, dominant_bin)
    candidates = compute_expected_candidates(num_classes, class_names, output_width, tensor)

    ref = {
        "exp": exp_name,
        "num_classes": num_classes,
        "class_names": class_names,
        "strides": STRIDES,
        "reg_max": REG_MAX,
        "input_size": INPUT_SIZE,
        "output_width": output_width,
        "output_height": OUTPUT_HEIGHT,
        "nms_threshold": NMS_THRESHOLD,
        "candidate_threshold": SCORE_THRESHOLD,
        "inputDescription": "synthetic decoder parity: class {} score={} dominant_bin={}".format(
            class_index, class_score, dominant_bin),
        "inputChecksum": sum(tensor),
        "inputElementCount": 3 * INPUT_SIZE * INPUT_SIZE,  # NCHW input element count, not output tensor
        "ncnn_meta": {
            "param_sha256": param_sha256,
            "bin_sha256": bin_sha256,
            "input_blob": "in0",
            "output_blob": "out0",
            "note": "synthetic decoder parity - not from NCNN inference"
        },
        "outputTensor": tensor,
        "candidates": candidates,
        "platform": "synthetic_decoder_parity",
        "note": "Synthetic decoder parity reference. NOT from NCNN inference. Tests decoder logic only."
    }
    return ref


def main():
    base_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "app", "src", "androidTest", "assets", "ncnn_parity"
    )

    # exp22: 4 classes, output_width=36, class 0 "Black Thread" score=0.85, dominant bin 5
    exp22_ref = generate_reference(
        exp_name="exp22_black_4class",
        num_classes=4,
        class_names=["Black Thread", "Black Nutsert", "Black Nut", "Black Bolt"],
        output_width=36,
        class_index=0,
        class_score=0.85,
        dominant_bin=5,
        param_sha256="B81B824FEA9FF949F72F3715A8F20C6EBE96C2792370DD80B7A7A69A65335960",
        bin_sha256="D3A16EDB715050B376F40B5F396FC748B984D781590AA1BF07B3F42A3D92A3D7",
    )

    # exp23: 2 classes, output_width=34, class 0 "White Nut" score=0.90, dominant bin 3
    exp23_ref = generate_reference(
        exp_name="exp23_white_2class",
        num_classes=2,
        class_names=["White Nut", "White Thread"],
        output_width=34,
        class_index=0,
        class_score=0.90,
        dominant_bin=3,
        param_sha256="AD45E2F3FCB6777A5E924AA9A3095C23B2C5F900632720C389D7816A1A390BDD",
        bin_sha256="1B662094CE94F4A3A8C899F40E1CB449E01AA10AE7A1ADDABCB92BFEF18DA35D",
    )

    for name, ref in [("exp22_decoder_parity.json", exp22_ref),
                       ("exp23_decoder_parity.json", exp23_ref)]:
        path = os.path.join(base_dir, name)
        with open(path, 'w') as f:
            json.dump(ref, f, indent=2)
        with open(path, 'rb') as f:
            sha = hashlib.sha256(f.read()).hexdigest()
        print("{}:".format(name))
        print("  SHA-256: {}".format(sha))
        print("  Tensor len: {}".format(len(ref['outputTensor'])))
        print("  Candidates: {}".format(len(ref['candidates'])))
        for c in ref['candidates']:
            print("    {} score={:.6f} point={} box={}".format(
                c['className'], c['score'], c['point'],
                [round(x, 4) for x in c['box']]))
        print()


if __name__ == "__main__":
    main()